defaultSemverRangePrefix: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      eslint-config-prettier: "*"
      eslint-plugin-prettier: "*"
      prettier: "*"
  styled-components@*:
    dependencies:
      babel-plugin-macros: "*"
