import { StrictMode, VFC } from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import { StyleWrapper } from '@sprice237/accounting-ui';
import { GqlProvider } from '@sprice237/accounting-gql';

import { App } from '$cmp/App';
import { useSchema } from './gql/useSchema';

// don't try to fix this unless prepared to navigate the rabbit hole that awaits
import gqlSchema from '!raw-loader!@sprice237/accounting-gql/dist/__autogenerated__/schema.graphql';

const portfolioId = '00000000-0000-0000-0000-000000000001';

const Root: VFC = () => {
  const graphqlSchema = useSchema(gqlSchema);

  if (!graphqlSchema) {
    return null;
  }

  return (
    <StrictMode>
      <GqlProvider
        uri="http://localhost:8080/graphql"
        schema={graphqlSchema}
        portfolioId={portfolioId}
      >
        <StyleWrapper>
          <Router>
            <App />
          </Router>
        </StyleWrapper>
      </GqlProvider>
    </StrictMode>
  );
};

ReactDOM.render(<Root />, document.getElementById('root'));
